#!/bin/bash
#Compile Script RiotMode

temp=`mktemp -d -t rm`
echo $temp
for dir in tags/*/
do
    dir=${dir%*/}
    riot $dir/src $dir/dist
    cp $dir/src/*.tag $temp
done
    
echo "======================="
echo "Compiling main dist..."    
riot $temp dist/RiotMode.js
rm -rf $temp

for i in `find mixins -name '*.js'` ; 
do 
    cat $i dist/RiotMode.js > tmp && mv tmp dist/RiotMode.js
done
